from collections.abc import Callable
from typing import ClassVar, Self

from _typeshed import Incomplete

__version__: str
pi_over_two: float
pi_over_four: float
negative_pi: float
negative_pi_over_two: float
sqrt_2: float

def normalize_angle(theta: float) -> float: ...
def negate_angle(theta: float) -> float: ...
def normalize_polar(r: float, theta: float) -> tuple[float, float]: ...

permitted_coordinate_types: tuple[()]

def permit_coordinate_type(t: Incomplete) -> Incomplete: ...

class Vector2Metaclass(type):
    def __call__(
        self,
        x: float = ...,
        y: float = ...,
        *,
        r: float = ...,
        theta: float = ...,
        r_squared: Incomplete = ...,
    ) -> Incomplete: ...

class Vector2(metaclass=Vector2Metaclass):
    __slots__ = ["x", "y", "r", "theta", "r_squared", "_cartesian", "_polar", "_hash"]  # noqa: RUF023 : keep sort order as source

    def __init__(
        self,
        x: float = ...,
        y: float = ...,
        *,
        r: float = ...,
        theta: float = ...,
        r_squared: float = ...,
    ) -> None: ...
    @classmethod
    def from_polar(cls, r: float, theta: float = ...) -> Self: ...
    @property
    def theta(self) -> float: ...
    def r(self) -> float: ...
    def polar(self) -> tuple[float, float]: ...
    def __getattr__(self, name: str) -> Incomplete: ...
    def __setattr__(self, name: str, value: Incomplete) -> Incomplete: ...
    def __len__(self) -> Incomplete: ...
    def __iter__(self) -> Incomplete: ...
    def __getitem__(self, index: int) -> Incomplete: ...
    def __setitem__(self, index: int, value: Incomplete) -> Incomplete: ...
    def __eq__(self, other: Incomplete) -> Incomplete: ...
    def __ne__(self, other: Incomplete) -> Incomplete: ...
    def __add__(self, other: Incomplete) -> Incomplete: ...
    def __radd__(self, other: Incomplete) -> Incomplete: ...
    def __sub__(self, other: Incomplete) -> Incomplete: ...
    def __rsub__(self, other: Incomplete) -> Incomplete: ...
    def __mul__(self, other: Incomplete) -> Incomplete: ...
    def __rmul__(self, other: Incomplete) -> Incomplete: ...
    def __truediv__(self, other: Incomplete) -> Incomplete: ...
    def __pos__(self) -> Incomplete: ...
    def __neg__(self) -> Incomplete: ...
    def __bool__(self) -> Incomplete: ...
    def __hash__(self) -> Incomplete: ...
    def almost_equal(self, other: Incomplete, places: Incomplete) -> Incomplete: ...
    def scaled(self, multiplier: Incomplete) -> Incomplete: ...
    def scaled_to_length(self, r: float) -> Incomplete: ...
    def normalized(self) -> Incomplete: ...
    def rotated(self, theta: float) -> Incomplete: ...
    def dot(self, other: Incomplete) -> Incomplete: ...
    def cross(self, other: Incomplete) -> Incomplete: ...
    def lerp(self, other: Incomplete, ratio: Incomplete) -> Incomplete: ...
    def vec_slerp(self, other: Incomplete, ratio: Incomplete) -> Incomplete: ...
    def pygame_slerp(
        self,
        other: Incomplete,
        ratio: float,
        *,
        reflected: Incomplete = None,
        epsilon: float = 1e-6,
    ) -> Incomplete: ...
    slerp: ClassVar[Callable[..., Incomplete]]
    def nlerp(self, other: Incomplete, ratio: Incomplete) -> Incomplete: ...

vector2_zero: Vector2
vector2_0_0: Vector2
vector2_1_0: Vector2
vector2_0_1: Vector2
vector2_1_1: Vector2
